module: satosa.micro_services.attribute_generation.AddSyntheticAttributes
name: AddSyntheticAttributes
config:
  synthetic_attributes:
    default:
      default:
        mail: "{{mail}}"
        schac_home_organisation: "{{schac_home_organisation}}"
        idp: "{{idp}}"
