apiVersion: v1
kind: Service
metadata:
  name: privacy-statement-service
  namespace: <YOUR-NAMESPACE>
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: privacy-statement
  type: ClusterIP
