apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cmservice
  name: cmservice-data
  namespace: <YOUR-NAMESPACE>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
